name: padel
description: "Padel Court Booking App — real-time booking, matchmaking, and admin management."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  firebase_storage: ^13.0.2
  firebase_database: ^12.4.2
  firebase_messaging: ^16.0.4
  flutter_local_notifications: ^19.4.2

  # Auth
  google_sign_in: ^6.3.0
  sign_in_with_apple: ^6.1.1
  crypto: ^3.0.5

  # State Management
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  equatable: ^2.0.7

  # Navigation
  go_router: ^15.1.2

  # UI / UX
  google_fonts: ^6.2.1
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  table_calendar: ^3.0.9

  # Utilities
  intl: ^0.20.2
  uuid: ^4.5.1
  url_launcher: ^6.3.1
  shared_preferences: ^2.5.3
  image_picker: ^1.2.2
  file_picker: ^11.0.2
  package_info_plus: ^9.0.1

  # Maps / Location
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^13.0.2

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
