// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8slTxwUTengbRQYAhPUXrJpqv_tw_lzk',
    appId: '1:297754277020:web:59c3223c91f6f3768b2959',
    messagingSenderId: '297754277020',
    projectId: 'padel-5bb05',
    authDomain: 'padel-5bb05.firebaseapp.com',
    storageBucket: 'padel-5bb05.firebasestorage.app',
    measurementId: 'G-LCQY64PP71',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzBoAEI3fvDB59L8IZ61yoeUaTjz3W5co',
    appId: '1:297754277020:android:624150418badf93d8b2959',
    messagingSenderId: '297754277020',
    projectId: 'padel-5bb05',
    storageBucket: 'padel-5bb05.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWGPUmoXg9o101q29rNd5U0s5iUvakGFE',
    appId: '1:297754277020:ios:6a54819a2ab003568b2959',
    messagingSenderId: '297754277020',
    projectId: 'padel-5bb05',
    storageBucket: 'padel-5bb05.firebasestorage.app',
    iosClientId: '297754277020-a9dle8q3q0n17o8l33fg9qks21j7bde5.apps.googleusercontent.com',
    iosBundleId: 'com.example.padel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWGPUmoXg9o101q29rNd5U0s5iUvakGFE',
    appId: '1:297754277020:ios:6a54819a2ab003568b2959',
    messagingSenderId: '297754277020',
    projectId: 'padel-5bb05',
    storageBucket: 'padel-5bb05.firebasestorage.app',
    iosClientId: '297754277020-a9dle8q3q0n17o8l33fg9qks21j7bde5.apps.googleusercontent.com',
    iosBundleId: 'com.example.padel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8slTxwUTengbRQYAhPUXrJpqv_tw_lzk',
    appId: '1:297754277020:web:7b10de4c8e4337e48b2959',
    messagingSenderId: '297754277020',
    projectId: 'padel-5bb05',
    authDomain: 'padel-5bb05.firebaseapp.com',
    storageBucket: 'padel-5bb05.firebasestorage.app',
    measurementId: 'G-90HLDVWNBG',
  );
}
